package com.developerjp.JieunMotivationalQ;

import android.content.Intent;
import android.os.Bundle;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import java.util.ArrayList;
import java.util.Objects;

public class ShowQuotes extends AppCompatActivity {

    private final ArrayList<String> quotesList = new ArrayList<>(); // Initialize the list here

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_show_quotes);

        // Grabs the value of the person clicked
        Intent intent = getIntent();
        String person = intent.getStringExtra("person");

        Toolbar toolbar = findViewById(R.id.toolbar_quotes);
        setSupportActionBar(toolbar);
        Objects.requireNonNull(getSupportActionBar()).setTitle(person);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);

        // Populate the array with data - the quotes to show
        assert person != null;
        showQuotes(person);

        // Set up the RecyclerView
        RecyclerView recyclerView = findViewById(R.id.recyclerView_quotes);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        MyRecyclerViewAdapterQuotes adapter = new MyRecyclerViewAdapterQuotes(this, quotesList);
        recyclerView.setAdapter(adapter);

    }

    @Override
    public boolean onSupportNavigateUp() {
        onBackPressed();
        return true;
    }
    
    private void showQuotes(String person) {
        quotesList.clear(); // Clear the list before adding new quotes

        //switch statement to show the correct quotes depending on which person was selected
        switch (person) {
            case "Success in Action":
                quotesList.add("The function of leadership is to produce more leaders, not more followers. - Ralph Nader");
                quotesList.add("Leadership is not about being in charge. It's about taking care of those in your charge. - Simon Sinek");
                quotesList.add("A leader is one who knows the way, goes the way, and shows the way. - John C. Maxwell");
                quotesList.add("The only way to do great work is to love what you do. - Steve Jobs");
                quotesList.add("Leadership is the capacity to translate vision into reality. - Warren Bennis");
                quotesList.add("The best way to predict your future is to create it. - Abraham Lincoln");
                quotesList.add("Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill");
                quotesList.add("Innovation distinguishes between a leader and a follower. - Steve Jobs");
                quotesList.add("Leadership is not about being the best. It's about making everyone else better. - Anonymous");
                quotesList.add("To lead people, walk behind them. - Lao Tzu");
                quotesList.add("Don't tell people how to do things, tell them what to do and let them surprise you with their results. - George S. Patton");
                quotesList.add("The quality of a leader is reflected in the standards they set for themselves. - Ray Kroc");
                quotesList.add("You don't need a title to be a leader. - Anonymous");
                quotesList.add("Leadership is not a position or a title, it is action and example. - Cory Booker");
                quotesList.add("Leadership is the art of getting someone to do something you want done because he wants to do it. - Dwight D. Eisenhower");
                quotesList.add("Leaders don't create followers, they create more leaders. - Tom Peters");
                quotesList.add("A leader is someone who demonstrates what's possible. - Mark Yarnell");
                quotesList.add("The growth and development of people is the highest calling of leadership. - Harvey S. Firestone");
                quotesList.add("Leadership is influence. - John C. Maxwell");
                quotesList.add("The best leaders are those most interested in surrounding themselves with assistants and associates smarter than they are. - John C. Maxwell");
                quotesList.add("Leadership is the ability to get extraordinary achievement from ordinary people. - Brian Tracy");
                quotesList.add("Don't be a boss. Be a leader. - Anonymous");
                quotesList.add("A good leader leads the people from above them. A great leader leads the people from within them. - M.D. Arnold");
                quotesList.add("It's not about being the best. It's about being better than you were yesterday. - Anonymous");
                quotesList.add("You manage things; you lead people. - Rear Admiral Grace Hopper");
                quotesList.add("Management is doing things right; leadership is doing the right things. - Peter Drucker");
                quotesList.add("Leadership is not about being in charge. It's about taking care of those in your charge. - Simon Sinek");
                quotesList.add("Leadership is not about being perfect. It's about having the courage to be vulnerable. - Brené Brown");
                quotesList.add("The greatest leader is not necessarily the one who does the greatest things. He is the one that gets the people to do the greatest things. - Ronald Reagan");
                quotesList.add("Leadership is the art of motivating a group of people to act toward achieving a common goal. - Anonymous");
                quotesList.add("The function of leadership is to produce more leaders, not more followers. - Ralph Nader");
                quotesList.add("A leader is one who knows the way, goes the way, and shows the way. - John C. Maxwell");
                quotesList.add("You don't lead by hitting people over the head—that's assault, not leadership. - Dwight D. Eisenhower");
                quotesList.add("Great leaders don't tell you what to do. They show you how it's done. - Anonymous");
                quotesList.add("A good leader makes people feel that they are at the very heart of things, not at the periphery. - Warren Bennis");
                quotesList.add("Leadership is the ability to inspire others to achieve a vision, even when that vision seems out of reach. - Anonymous");
                quotesList.add("Leadership is the art of getting someone to do something you want done because he wants to do it. - Dwight D. Eisenhower");
                quotesList.add("Leadership is not about being in charge. It's about taking care of those in your charge. - Simon Sinek");
                quotesList.add("Leadership is action, not position. - Donald H. McGannon");
                quotesList.add("Leadership is about making others better as a result of your presence and making sure that impact lasts in your absence. - Sheryl Sandberg");
                quotesList.add("The most effective way to do it, is to do it. - Amelia Earhart");
                quotesList.add("In leadership, the most important thing is not authority, it's trust. - Anonymous");
                quotesList.add("People buy into the leader before they buy into the vision. - John C. Maxwell");
                quotesList.add("A true leader has the confidence to stand alone, the courage to make tough decisions, and the compassion to listen to the needs of others. - Douglas MacArthur");
                quotesList.add("A leader is someone who can adapt to any situation and create change. - Anonymous");
                quotesList.add("Effective leadership is not about making speeches or being liked; leadership is defined by results not attributes. - Peter Drucker");
                quotesList.add("The greatest leader is not necessarily the one who does the greatest things. He is the one that gets the people to do the greatest things. - Ronald Reagan");
                quotesList.add("Don't just be a leader. Be the kind of leader others want to follow. - Anonymous");
                quotesList.add("Leadership is about making others better as a result of your presence and making sure that impact lasts in your absence. - Sheryl Sandberg");
                quotesList.add("Success is the sum of small efforts, repeated day in and day out. - Robert Collier");
                quotesList.add("A great leader is not a person who does great things. A great leader is a person who inspires others to do great things. - Ronald Reagan");
                break;

            case "Proverbs":
                quotesList.add("A little impatience will spoil great plans. - Chinese Proverb");
                quotesList.add("Do not look where you fell, but where you slipped. - African Proverb");
                quotesList.add("He who asks is a fool for five minutes, but he who does not ask remains a fool forever. - Chinese Proverb");
                quotesList.add("If you want to go fast, go alone. If you want to go far, go together. - African Proverb");
                quotesList.add("A tree is known by its fruit. - English Proverb");
                quotesList.add("If the wind will not serve, take to the oars. - Latin Proverb");
                quotesList.add("A stumble may prevent a fall. - English Proverb");
                quotesList.add("Wisdom is like fire. People take it from others. - Hema Proverb, Congo");
                quotesList.add("The best time to plant a tree was twenty years ago. The second best time is now. - Chinese Proverb");
                quotesList.add("To go fast, walk alone. To go far, walk together. - African Proverb");
                quotesList.add("The nail that sticks out gets hammered down. - Japanese Proverb");
                quotesList.add("It takes a village to raise a child. - African Proverb");
                quotesList.add("Do not put your trust in money, but put your money in trust. - Scottish Proverb");
                quotesList.add("A closed mouth catches no flies. - Italian Proverb");
                quotesList.add("Where there is no vision, the people perish. - Hebrew Proverb");
                quotesList.add("The old horse knows the way. - Chinese Proverb");
                quotesList.add("A clear conscience is a soft pillow. - German Proverb");
                quotesList.add("He who is afraid of asking is ashamed of learning. - Danish Proverb");
                quotesList.add("A single bracelet does not jingle. - Congolese Proverb");
                quotesList.add("The path is made by walking. - Spanish Proverb");
                quotesList.add("The best armor is to keep out of range. - Italian Proverb");
                quotesList.add("Even a small star shines in the darkness. - Finnish Proverb");
                quotesList.add("Words are silver, silence is golden. - Swiss Proverb");
                quotesList.add("A bird does not sing because it has an answer. It sings because it has a song. - Chinese Proverb");
                quotesList.add("Two heads are better than one. - English Proverb");
                quotesList.add("He who knows others is wise; he who knows himself is enlightened. - Chinese Proverb");
                quotesList.add("A penny saved is a penny earned. - American Proverb");
                quotesList.add("All that glitters is not gold. - English Proverb");
                quotesList.add("Fall seven times, stand up eight. - Japanese Proverb");
                quotesList.add("A man who uses force is afraid of reasoning. - Kenyan Proverb");
                quotesList.add("To understand your parents' love, bear your own children. - Chinese Proverb");
                quotesList.add("A friend's eye is a good mirror. - Irish Proverb");
                quotesList.add("If you chase two rabbits, you will not catch either one. - Russian Proverb");
                quotesList.add("Do good and throw it in the sea. - Egyptian Proverb");
                quotesList.add("A hungry belly has no ears. - Jamaican Proverb");
                quotesList.add("One hand washes the other. - German Proverb");
                quotesList.add("A drop of wisdom is better than a sea of gold. - Greek Proverb");
                quotesList.add("Beauty is in the eye of the beholder. - English Proverb");
                quotesList.add("The eye cannot see itself. - Filipino Proverb");
                quotesList.add("Where there is love, there is no darkness. - Burundian Proverb");
                quotesList.add("It is not the strongest of the species that survives, nor the most intelligent, but the one most responsive to change. - Darwin Proverb");
                quotesList.add("A good husband is healthy and absent. - Japanese Proverb");
                quotesList.add("A fool and his money are soon parted. - English Proverb");
                quotesList.add("A leopard does not change his spots. - African Proverb");
                quotesList.add("Good fences make good neighbors. - American Proverb");
                quotesList.add("Even a clock that does not work is right twice a day. - Polish Proverb");
                quotesList.add("When in Rome, do as the Romans do. - Latin Proverb");
                quotesList.add("He who has health, has hope. And he who has hope, has everything. - Arabian Proverb");
                quotesList.add("A bird in the hand is worth two in the bush. - English Proverb");
                quotesList.add("The enemy of my enemy is my friend. - Arabic Proverb");
                quotesList.add("When the character of a man is not clear to you, look at his friends. - Japanese Proverb");
                quotesList.add("There is no shame in not knowing; the shame lies in not finding out. - Russian Proverb");
                quotesList.add("The beginning is the half of every action. - Greek Proverb");
                quotesList.add("There is no time like the present. - English Proverb");
                quotesList.add("A friend in need is a friend indeed. - English Proverb");
                quotesList.add("Do not count your chickens before they hatch. - English Proverb");
                quotesList.add("The early bird catches the worm. - English Proverb");
                quotesList.add("One who is not wise with words is a fool. - French Proverb");
                quotesList.add("Hope for the best, prepare for the worst. - English Proverb");
                quotesList.add("Still waters run deep. - English Proverb");
                quotesList.add("An ounce of prevention is worth a pound of cure. - American Proverb");
                quotesList.add("The pen is mightier than the sword. - English Proverb");
                quotesList.add("There is no place like home. - English Proverb");
                quotesList.add("Better late than never. - Latin Proverb");
                quotesList.add("Do not wear out your welcome. - Japanese Proverb");
                quotesList.add("When spider webs unite, they can tie up a lion. - Ethiopian Proverb");
                quotesList.add("What goes around comes around. - English Proverb");
                quotesList.add("God gives nuts to those who have no teeth. - Arabic Proverb");
                quotesList.add("Even the stones of the river are friends in the end. - African Proverb");
                quotesList.add("He who treads softly goes far. - Portuguese Proverb");
                quotesList.add("You reap what you sow. - English Proverb");
                quotesList.add("Wisdom is like a baobab tree; no one individual can embrace it. - Ghanaian Proverb");
                quotesList.add("The longest journey begins with a single step. - Chinese Proverb");
                quotesList.add("A house divided cannot stand. - Biblical Proverb");
                quotesList.add("Strike while the iron is hot. - English Proverb");
                quotesList.add("The squeaky wheel gets the grease. - American Proverb");
                quotesList.add("A bad workman blames his tools. - English Proverb");
                quotesList.add("Actions speak louder than words. - English Proverb");
                quotesList.add("Great minds think alike. - English Proverb");
                quotesList.add("Necessity is the mother of invention. - Greek Proverb");
                quotesList.add("Old habits die hard. - English Proverb");
                quotesList.add("Where there's a will, there's a way. - English Proverb");
                quotesList.add("Cleanliness is next to godliness. - English Proverb");
                quotesList.add("You can't judge a book by its cover. - English Proverb");
                quotesList.add("Don't put all your eggs in one basket. - English Proverb");
                quotesList.add("Practice makes perfect. - English Proverb");
                quotesList.add("Honesty is the best policy. - English Proverb");
                quotesList.add("Necessity knows no law. - Latin Proverb");
                quotesList.add("The grass is always greener on the other side. - English Proverb");
                quotesList.add("One who looks only at the outside is easily deceived. - Japanese Proverb");
                quotesList.add("Even a thousand-mile journey begins with the first step. - Japanese Proverb");
                quotesList.add("Fortune favors the bold. - Latin Proverb");
                quotesList.add("No pain, no gain. - English Proverb");
                quotesList.add("To teach is to learn twice. - French Proverb");
                break;

            case "Woman Power":
                quotesList.add("I am not free while any woman is unfree, even when her shackles are very different from my own. - Audre Lorde");
                quotesList.add("Do not wait for someone else to come and speak for you. It's you who can change the world. - Malala Yousafzai");
                quotesList.add("I have learned over the years that when one's mind is made up, this diminishes fear. - Rosa Parks");
                quotesList.add("One child, one teacher, one book, one pen can change the world. - Malala Yousafzai");
                quotesList.add("Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. - Helen Keller");
                quotesList.add("If you want something said, ask a man; if you want something done, ask a woman. - Margaret Thatcher");
                quotesList.add("Do not bring people in your life who weigh you down. And trust your instincts – good relationships feel good. - Oprah Winfrey");
                quotesList.add("We realize the importance of our voices only when we are silenced. - Malala Yousafzai");
                quotesList.add("Women belong in all places where decisions are being made. It shouldn't be that women are the exception. - Ruth Bader Ginsburg");
                quotesList.add("Success isn't about how much money you make; it's about the difference you make in people's lives. - Michelle Obama");
                quotesList.add("When the whole world is silent, even one voice becomes powerful. - Malala Yousafzai");
                quotesList.add("I would like to be known as an intelligent woman, a courageous woman, a loving woman, a woman who teaches by being. - Maya Angelou");
                quotesList.add("It is our choices that show what we truly are, far more than our abilities. - J.K. Rowling");
                quotesList.add("If you don't risk anything, you risk even more. - Erica Jong");
                quotesList.add("Leadership is about making others better as a result of your presence and making sure that impact lasts in your absence. - Sheryl Sandberg");
                quotesList.add("Every woman's success should be an inspiration to another. We're strongest when we cheer each other on. - Serena Williams");
                quotesList.add("Never doubt that you are valuable and powerful and deserving of every chance and opportunity in the world to pursue your dreams. - Hillary Clinton");
                quotesList.add("I am no bird; and no net ensnares me: I am a free human being with an independent will. - Charlotte Brontë");
                quotesList.add("It's one of the greatest gifts you can give yourself, to forgive. Forgive everybody. - Maya Angelou");
                quotesList.add("The most difficult thing is the decision to act, the rest is merely tenacity. - Amelia Earhart");
                quotesList.add("I raise up my voice – not so I can shout but so that those without a voice can be heard. - Malala Yousafzai");
                quotesList.add("It's not about being perfect. It's about effort. And when you implement that effort into your life, every single day, that's where transformation happens. - Jillian Michaels");
                quotesList.add("We don't develop courage by being happy every day. We develop it by surviving difficult times and challenging adversity. - Barbara De Angelis");
                quotesList.add("I am grateful to be a woman. I must have done something great in another life. - Maya Angelou");
                quotesList.add("I have chosen to no longer be apologetic for my femaleness and my femininity. And I want to be respected in all of my femaleness because I deserve to be. - Chimamanda Ngozi Adichie");
                quotesList.add("You may not control all the events that happen to you, but you can decide not to be reduced by them. - Maya Angelou");
                quotesList.add("You can waste your lives drawing lines. Or you can live your life crossing them. - Shonda Rhimes");
                quotesList.add("Power is not given to you. You have to take it. - Beyoncé Knowles");
                quotesList.add("I do not wish women to have power over men; but over themselves. - Mary Wollstonecraft");
                quotesList.add("If you want to fly, you have to give up the things that weigh you down. - Toni Morrison");
                quotesList.add("No one can make you feel inferior without your consent. - Eleanor Roosevelt");
                quotesList.add("Life is not easy for any of us. But what of that? We must have perseverance and, above all, confidence in ourselves. - Marie Curie");
                quotesList.add("Don't let anyone speak for you, and don't rely on others to fight for you. - Michelle Obama");
                quotesList.add("To be a woman is to know you must work twice as hard and achieve twice as much, but to never give up. - Meryl Streep");
                quotesList.add("Think like a queen. A queen is not afraid to fail. Failure is another stepping stone to greatness. - Oprah Winfrey");
                quotesList.add("Courage is like a muscle. We strengthen it by use. - Ruth Gordon");
                quotesList.add("You have to have confidence in your ability, and then be tough enough to follow through. - Rosalynn Carter");
                quotesList.add("I am not afraid of storms, for I am learning how to sail my ship. - Louisa May Alcott");
                quotesList.add("The way I see it, if you want the rainbow, you gotta put up with the rain. - Dolly Parton");
                quotesList.add("Don't wait around for other people to be happy for you. Any happiness you get, you've got to make yourself. - Alice Walker");
                quotesList.add("The most effective way to do it, is to do it. - Amelia Earhart");
                quotesList.add("The truth will set you free, but first it will piss you off. - Gloria Steinem");
                quotesList.add("Do what you feel in your heart to be right—for you'll be criticized anyway. - Eleanor Roosevelt");
                quotesList.add("What you do makes a difference, and you have to decide what kind of difference you want to make. - Jane Goodall");
                quotesList.add("Just don't give up trying to do what you really want to do. Where there's love and inspiration, I don't think you can go wrong. - Ella Fitzgerald");
                quotesList.add("Do not bring people in your life who weigh you down. And trust your instincts – good relationships feel good. - Oprah Winfrey");
                quotesList.add("You may encounter many defeats, but you must not be defeated. - Maya Angelou");
                quotesList.add("You deserve to be here. You deserve to exist. You deserve to take up space in this world of men. - Michaela Coel");
                quotesList.add("I have chosen to no longer be apologetic for my femaleness and my femininity. - Chimamanda Ngozi Adichie");
                quotesList.add("If I stop to kick every barking dog, I am not going to get where I'm going. - Jackie Joyner-Kersee");
                quotesList.add("A strong woman stands up for herself. A stronger woman stands up for everyone else. - Unknown");
                quotesList.add("Don't let anyone rob you of your imagination, your creativity, or your curiosity. - Mae Jemison");
                quotesList.add("My mother told me to be a lady. And for her, that meant be your own person, be independent. - Ruth Bader Ginsburg");
                quotesList.add("I do not wish them [women] to have power over men; but over themselves. - Mary Wollstonecraft");
                quotesList.add("Dreams are lovely. But they are just dreams. Fleeting, ephemeral, pretty. But dreams do not come true just because you dream them. It's hard work that makes things happen. - Shonda Rhimes");
                quotesList.add("Doubt is a killer. You just have to know who you are and what you stand for. - Jennifer Lopez");
                quotesList.add("I am deliberate and afraid of nothing. - Audre Lorde");
                quotesList.add("You may not always have a comfortable life and you will not always be able to solve all the world's problems, but don't ever underestimate the importance you can have. - Michelle Obama");
                quotesList.add("We cannot all succeed when half of us are held back. - Malala Yousafzai");
                quotesList.add("No one can make you feel inferior without your consent. - Eleanor Roosevelt");
                quotesList.add("The best protection any woman can have is courage. - Elizabeth Cady Stanton");
                quotesList.add("What you want exists. Don't settle until you get it. - Jay Shetty");
                quotesList.add("Define success on your own terms, achieve it by your own rules, and build a life you're proud to live. - Anne Sweeney");
                quotesList.add("A woman is the full circle. Within her is the power to create, nurture, and transform. - Diane Mariechild");
                quotesList.add("The question isn't who is going to let me; it's who is going to stop me. - Ayn Rand");
                quotesList.add("The most courageous act is still to think for yourself. Aloud. - Coco Chanel");
                quotesList.add("I am not interested in competing with anyone. I hope we all make it. - Erica Cook");
                quotesList.add("I'm tough, I'm ambitious, and I know exactly what I want. If that makes me a bitch, okay. - Madonna");
                quotesList.add("There's power in allowing yourself to be known and heard, in owning your unique story, in using your authentic voice. - Michelle Obama");
                quotesList.add("You are never too small to make a difference. - Greta Thunberg");
                quotesList.add("Without leaps of imagination, or dreaming, we lose the excitement of possibilities. - Gloria Steinem");
                quotesList.add("Don't be afraid. Be focused. Be determined. Be hopeful. Be empowered. - Michelle Obama");
                quotesList.add("You don't have to play masculine to be a strong woman. - Mary Elizabeth Winstead");
                quotesList.add("Everyone has inside of her a piece of good news. The good news is that you don't know how great you can be. - Anne Frank");
                quotesList.add("You get what you settle for. - Thelma and Louise");
                quotesList.add("Life is very interesting… in the end, some of your greatest pains become your greatest strengths. - Drew Barrymore");
                quotesList.add("As a woman I have no country. As a woman my country is the whole world. - Virginia Woolf");
                quotesList.add("The beauty of standing up for your rights is others see you standing and stand up as well. - Cassandra Duffy");
                quotesList.add("Feminism is the radical notion that women are human beings. - Cheris Kramarae");
                quotesList.add("Above all, be the heroine of your life, not the victim. - Nora Ephron");
                quotesList.add("The difference between a broken community and a thriving one is the presence of women who are valued. - Michelle Obama");
                break;

            case "Through Storm":
                quotesList.add("You don't have to control your thoughts. You just have to stop letting them control you. - Dan Millman");
                quotesList.add("This too shall pass. It may pass like a kidney stone, but it will pass.");
                quotesList.add("Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis");
                quotesList.add("You may not control all the events that happen to you, but you can decide not to be reduced by them. - Maya Angelou");
                quotesList.add("When you come out of the storm, you won't be the same person who walked in. That's what the storm is all about. - Haruki Murakami");
                quotesList.add("You don't have to see the whole staircase, just take the first step. - Martin Luther King Jr.");
                quotesList.add("You may have to fight a battle more than once to win it. - Margaret Thatcher");
                quotesList.add("Sometimes the bravest and most important thing you can do is just show up. - Brené Brown");
                quotesList.add("Our greatest glory is not in never falling, but in rising every time we fall. - Confucius");
                quotesList.add("When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. - Henry Ford");
                quotesList.add("Difficulties in life are intended to make us better, not bitter.");
                quotesList.add("When you go through deep waters, I will be with you. - Isaiah 43:2");
                quotesList.add("Believe you can and you're halfway there. - Theodore Roosevelt");
                quotesList.add("A hero is an ordinary individual who finds the strength to persevere and endure in spite of overwhelming obstacles. - Christopher Reeve");
                quotesList.add("Life isn't about waiting for the storm to pass; it's about learning to dance in the rain. - Vivian Greene");
                quotesList.add("We must accept finite disappointment, but never lose infinite hope. - Martin Luther King Jr.");
                quotesList.add("The darkest hour has only sixty minutes. - Morris Mandel");
                quotesList.add("Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill");
                quotesList.add("Do not lose hope, please believe that there are a thousand beautiful things waiting for you.");
                quotesList.add("Pain is inevitable. Suffering is optional. - Haruki Murakami");
                quotesList.add("It's not whether you get knocked down, it's whether you get up. - Vince Lombardi");
                quotesList.add("You're allowed to scream, you're allowed to cry, but do not give up.");
                quotesList.add("Although the world is full of suffering, it is also full of the overcoming of it. - Helen Keller");
                quotesList.add("Sometimes when you're in a dark place you think you've been buried, but actually you've been planted.");
                quotesList.add("You are stronger than you think, braver than you believe, and smarter than you know.");
                quotesList.add("Strength grows in the moments when you think you can't go on but keep going anyway.");
                quotesList.add("Out of difficulties grow miracles. - Jean de La Bruyère");
                quotesList.add("One small crack does not mean that you are broken; it means that you were put to the test and you didn't fall apart.");
                quotesList.add("Every day may not be good, but there is something good in every day.");
                quotesList.add("You're not going to master the rest of your life in one day. Just relax, master the day, then keep doing that every day.");
                quotesList.add("Tough times never last, but tough people do. - Robert H. Schuller");
                quotesList.add("Never let a bad situation bring out the worst in you. Be strong and choose to be positive.");
                quotesList.add("Just because you're struggling does not mean you're failing. Every great success requires some kind of struggle to get there.");
                quotesList.add("Difficult roads often lead to beautiful destinations.");
                quotesList.add("Sometimes, all you can do is lie in bed, and hope to fall asleep before you fall apart.");
                quotesList.add("The human spirit is stronger than anything that can happen to it. - C.C. Scott");
                quotesList.add("It's okay to be a glow stick; sometimes we have to break before we shine.");
                quotesList.add("The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela");
                quotesList.add("Even if happiness forgets you a little bit, never completely forget about it. - Jacques Prévert");
                quotesList.add("Every adversity, every failure, every heartache carries with it the seed of an equal or greater benefit. - Napoleon Hill");
                quotesList.add("You've survived 100% of your worst days. Keep going.");
                quotesList.add("Hope is the thing with feathers that perches in the soul and sings the tune without the words and never stops at all. - Emily Dickinson");
                quotesList.add("The only way out of the labyrinth of suffering is to forgive. - John Green");
                quotesList.add("The harder the battle, the sweeter the victory.");
                quotesList.add("There is no mountain that cannot be climbed, no path that cannot be taken.");
                quotesList.add("The struggle you're in today is developing the strength you need for tomorrow.");
                quotesList.add("Keep going. Your hardest times often lead to the greatest moments of your life.");
                quotesList.add("What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson");
                quotesList.add("When we are no longer able to change a situation, we are challenged to change ourselves. - Viktor Frankl");
                quotesList.add("Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.' - Mary Anne Radmacher");
                quotesList.add("You never know how strong you are until being strong is your only choice. - Bob Marley");
                quotesList.add("Sometimes the bad things that happen in our lives put us directly on the path to the best things that will ever happen to us.");
                quotesList.add("Don't let yesterday take up too much of today. - Will Rogers");
                quotesList.add("Rise above the storm and you will find the sunshine. - Mario Fernández");
                quotesList.add("If you are going through hell, keep going. - Winston Churchill");
                quotesList.add("You have been assigned this mountain to show others it can be moved.");
                quotesList.add("Sometimes, all we need is a fresh start.");
                quotesList.add("Your life isn't falling apart; it's falling into place.");
                quotesList.add("The pain you feel today will be the strength you feel tomorrow.");
                quotesList.add("One day you will tell your story of how you've overcome what you're going through now, and it will become part of someone else's survival guide.");
                quotesList.add("If you stumble, make it part of the dance.");
                quotesList.add("Trust yourself. You've survived a lot, and you'll survive whatever is coming.");
                quotesList.add("Don't give up now; your breakthrough may be just around the corner.");
                quotesList.add("Let it hurt. Let it bleed. Let it heal. And let it go.");
                quotesList.add("We can't direct the wind, but we can adjust the sails. - Dolly Parton");
                quotesList.add("Even the darkest night will end, and the sun will rise. - Victor Hugo");
                quotesList.add("It is often in the darkest skies that we see the brightest stars.");
                quotesList.add("You're allowed to scream, you're allowed to cry, but do not give up.");
                quotesList.add("Healing takes time, and asking for help is a courageous step.");
                quotesList.add("Even broken crayons can still color.");
                quotesList.add("Your value doesn't decrease based on someone's inability to see your worth.");
                quotesList.add("Take life one day at a time. One step at a time.");
                quotesList.add("At any given moment, you have the power to say: this is not how the story is going to end.");
                quotesList.add("When life gives you a hundred reasons to cry, show life that you have a thousand reasons to smile.");
                quotesList.add("Remember, the greatest lesson is found in the storm.");
                quotesList.add("Strength does not come from physical capacity. It comes from an indomitable will. - Mahatma Gandhi");
                quotesList.add("In the end, we only regret the chances we didn't take.");
                quotesList.add("Never let a stumble in the road be the end of the journey.");
                quotesList.add("The comeback is always stronger than the setback.");
                quotesList.add("If it doesn't challenge you, it won't change you.");
                quotesList.add("Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.");
                quotesList.add("Life is tough, my darling, but so are you. - Stephanie Bennett Henry");
                quotesList.add("Every day is a second chance.");
                quotesList.add("Be gentle with yourself. You're doing the best you can.");
                quotesList.add("Letting go doesn't mean giving up, but rather accepting that there are things that cannot be.");
                quotesList.add("Someday, all the love you've given away will find its way back to you.");
                quotesList.add("Don't quit. You are already in pain. You are already hurt. Get a reward from it.");
                quotesList.add("Be strong now because things will get better. It might be stormy now, but it can't rain forever.");
                quotesList.add("And sometimes, against all odds, against all logic, we still hope.");
                quotesList.add("Life has a funny way of working out just when you start to believe it never will.");
                quotesList.add("If you feel like you're losing everything, remember that trees lose their leaves every year and still stand tall and wait for better days to come.");
                quotesList.add("Storms make trees take deeper roots. - Dolly Parton");
                quotesList.add("You are not the storm, but the unshakable calm at its center.");
                quotesList.add("The soul always knows what to do to heal itself. The challenge is to silence the mind. - Caroline Myss");
                quotesList.add("Every storm runs out of rain, just like every night turns into day. - Gary Allan");
                quotesList.add("When it is dark enough, you can see the stars. - Ralph Waldo Emerson");
                quotesList.add("The strongest steel is forged in the hottest fire.");
                quotesList.add("The sun will shine again after the storm. Keep holding on.");
                quotesList.add("Adversity is the first path to truth. - Lord Byron");
                quotesList.add("You can't calm the storm, so stop trying. What you can do is calm yourself. The storm will pass.");
                quotesList.add("Within the chaos of the storm lies the seed of opportunity.");
                quotesList.add("Rise with the sun and let it burn away yesterday's shadows.");
                quotesList.add("The darkest storms hold the brightest rainbows.");
                quotesList.add("Every storm in your life is followed by a rainbow of blessings.");
                quotesList.add("You were given this life because you are strong enough to live it.");
                quotesList.add("Remember, you have survived 100% of your hardest days.");
                quotesList.add("Life isn't about surviving the storm; it's about learning to dance in the rain.");
                quotesList.add("You are not alone in this storm; someone always cares.");
                quotesList.add("Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman");
                quotesList.add("Do not fear the storm; it simply reveals your inner strength.");
                quotesList.add("You are more resilient than the storm you're facing.");
                quotesList.add("The storm is a teacher; listen closely to its lessons.");
                quotesList.add("After the rain, there is growth. You will flourish.");
                break;

            case "Confucius":
                quotesList.add("It does not matter how slowly you go as long as you do not stop.");
                quotesList.add("Our greatest glory is not in never falling, but in rising every time we fall.");
                quotesList.add("Real knowledge is to know the extent of one's ignorance.");
                quotesList.add("The man who moves a mountain begins by carrying away small stones.");
                quotesList.add("What you do not wish for yourself, do not do to others.");
                quotesList.add("Ignorance is the night of the mind, but a night without moon and star.");
                quotesList.add("To see what is right and not do it is the worst cowardice.");
                quotesList.add("When we see men of a contrary character, we should turn inwards and examine ourselves.");
                quotesList.add("He who learns but does not think, is lost. He who thinks but does not learn is in great danger.");
                quotesList.add("Wherever you go, go with all your heart.");
                quotesList.add("In a country well governed, poverty is something to be ashamed of. In a country badly governed, wealth is something to be ashamed of.");
                quotesList.add("The superior man is modest in his speech but exceeds in his actions.");
                quotesList.add("Learning without thought is labor lost; thought without learning is perilous.");
                quotesList.add("He who conquers himself is the mightiest warrior.");
                quotesList.add("Wheresoever you go, go with all your heart.");
                quotesList.add("When you are laboring for others, let it be with the same zeal as if it were for yourself.");
                quotesList.add("To know what is right and not do it is the worst cowardice.");
                quotesList.add("The superior man understands what is right; the inferior man understands what will sell.");
                quotesList.add("The journey of a thousand miles begins with one step.");
                quotesList.add("A man who uses force is afraid of reasoning.");
                quotesList.add("Study the past if you would define the future.");
                quotesList.add("The strength of a nation derives from the integrity of the home.");
                quotesList.add("Better a diamond with a flaw than a pebble without.");
                quotesList.add("It is better to light one small candle than to curse the darkness.");
                quotesList.add("Respect yourself and others will respect you.");
                quotesList.add("The wise find pleasure in water; the virtuous find pleasure in hills. The wise are active; the virtuous are tranquil. The wise are joyful; the virtuous are long-lived.");
                quotesList.add("To be wronged is nothing unless you continue to remember it.");
                quotesList.add("He who asks a question is a fool for a minute; he who does not ask is a fool for life.");
                quotesList.add("Success depends upon previous preparation, and without such preparation there is sure to be failure.");
                quotesList.add("A gentle man would be ashamed should his deeds not match his words.");
                quotesList.add("To see what is right and not do it is the mark of a small man.");
                quotesList.add("The more man meditates upon good thoughts, the better will be his world and the world at large.");
                quotesList.add("He who cherishes his life is able to make it long.");
                quotesList.add("The superior man thinks of virtue; the small man thinks of comfort.");
                quotesList.add("He who learns from others is wise; he who learns from himself is enlightened.");
                quotesList.add("Be strict with yourself but lenient with others.");
                quotesList.add("He who wishes to be rich in a day will be hanged in a year.");
                quotesList.add("The man who has committed a mistake and doesn't correct it is committing another mistake.");
                quotesList.add("The cautious seldom err.");
                quotesList.add("The noble-minded are calm and steady. Little people are forever fussing and fretting.");
                quotesList.add("One who believes in the virtue of one's self has the right to change the world.");
                quotesList.add("The man who does not understand the power of love is not worthy of it.");
                quotesList.add("In the face of danger, the noble man remains steadfast.");
                quotesList.add("A wise man will always think of the consequences before he acts.");
                quotesList.add("It is more shameful to distrust our friends than to be deceived by them.");
                quotesList.add("He who speaks without modesty will find it difficult to make his words good.");
                quotesList.add("Those who cannot forgive others break the bridge over which they themselves must pass.");
                quotesList.add("We should not treat our friends as we would like our enemies to treat us.");
                quotesList.add("The man who moves a mountain begins by carrying away small stones.");
                quotesList.add("When a man does not recognize the power of virtue, it is time to leave him alone.");
                quotesList.add("It is better to be hated for what you are than to be loved for what you are not.");
                quotesList.add("Be firm in your convictions, and stick to your ideals.");
                quotesList.add("The noble-minded are like the stars, which reflect the light of heaven upon the earth.");
                quotesList.add("The wise are those who understand the importance of what they do and say.");
                quotesList.add("He who has no confidence has no love.");
                quotesList.add("It is the way of the wise to study carefully before they act.");
                quotesList.add("A man should be like water; it benefits all things, yet does not strive.");
                quotesList.add("To be at peace with oneself is to be at peace with the world.");
                quotesList.add("He who is content is rich.");
                quotesList.add("The wise man will always keep his promises.");
                quotesList.add("The man who does not think is a man who will not achieve.");
                quotesList.add("He who acts with a pure heart will always find success.");
                quotesList.add("The virtuous man is like a tree planted by the rivers of water.");
                quotesList.add("What the superior man seeks is in himself; what the small man seeks is in others.");
                quotesList.add("The wise man understands that he is only as strong as the people around him.");
                quotesList.add("A man's character is judged by his actions, not his words.");
                quotesList.add("He who knows that he has enough is rich.");
                quotesList.add("A good friend is like a good book; it can change your life.");
                quotesList.add("Virtue is not left to stand alone. He who practices it will have neighbors.");
                quotesList.add("Learning is a treasure that will follow its owner everywhere.");
                quotesList.add("To see what is right and not do it is the mark of a small man.");
                quotesList.add("The one who is able to accept his faults will be able to correct them.");
                quotesList.add("The wise man will always have a plan.");
                quotesList.add("When one is happy, one does not want to harm others.");
                quotesList.add("The superior man is the one who speaks little and acts much.");
                quotesList.add("He who wishes to be rich in a day will be hanged in a year.");
                quotesList.add("The wise man does not lay his plans lightly, but weighs them carefully.");
                quotesList.add("The man who thinks he can and the man who thinks he can't are both right.");
                quotesList.add("The noble man understands that there is no greater virtue than humility.");
                quotesList.add("He who is without virtue cannot endure for long.");
                quotesList.add("The wise man speaks because he has something to say; the fool speaks because he has to say something.");
                quotesList.add("A wise man will not be angry with those who are less fortunate than himself.");
                quotesList.add("To be truly wise, one must first be truly humble.");
                quotesList.add("The superior man acts before he speaks, and afterwards speaks according to his action.");
                quotesList.add("He who is too busy to care for the needs of others will eventually find himself in need.");
                quotesList.add("He who does not care for his character will never be able to care for his reputation.");
                quotesList.add("The man who is afraid of losing has already lost.");
                quotesList.add("The wise man does not compare himself to others, but strives to be better than he was yesterday.");
                quotesList.add("The path of virtue is a road to peace.");
                quotesList.add("He who is humble is wise.");
                quotesList.add("The noble man understands that knowledge is power, and that wisdom is its application.");
                quotesList.add("The wise man will always listen to others before speaking.");
                quotesList.add("The man who is at peace with himself is at peace with the world.");
                quotesList.add("Virtue is not in the words we say but in the actions we take.");
                quotesList.add("The wise understand the importance of harmony in their relationships.");
                quotesList.add("One who is wise does not argue with fools.");
                quotesList.add("The man who understands himself is on the road to understanding others.");
                quotesList.add("Those who are wise know that there is always more to learn.");
                quotesList.add("He who is not content is not happy.");
                quotesList.add("You are the only person who can limit your greatness.");
                quotesList.add("Self-confidence is the first requisite to great undertakings. - Samuel Johnson");
                quotesList.add("Believe in your dreams, and they may come true; believe in yourself, and they will come true.");
                quotesList.add("The most important relationship in your life is the one you have with yourself.");
                quotesList.add("Your value doesn't decrease based on someone's inability to see your worth.");
                quotesList.add("You were born to be real, not to be perfect.");
                quotesList.add("If you're searching for that one person that will change your life, take a look in the mirror.");
                quotesList.add("When you believe in yourself, you set the foundation for greatness.");
                quotesList.add("To love yourself is to understand you don't need validation from others.");
                quotesList.add("You were born to be a star, don't let anyone dim your shine.");
                quotesList.add("Trust yourself and trust the process of life. Everything is unfolding as it should.");
                quotesList.add("Don't be afraid to shine. The world needs your light.");
                quotesList.add("Be your own biggest cheerleader.");
                quotesList.add("You are worthy of all the love, success, and happiness you dream of.");
                quotesList.add("Believe in your abilities. You are capable of more than you know.");
                quotesList.add("The only limit to your success is your willingness to believe in it.");
                quotesList.add("You don't have to be perfect, just be yourself and own it.");
                quotesList.add("Self-doubt is the enemy of progress. Trust in yourself and take action.");
                quotesList.add("No one else can play your role, and no one can steal your dreams.");
                quotesList.add("The real magic happens when you believe in yourself.");
                quotesList.add("You are more than enough, and you have everything you need to succeed.");
                quotesList.add("Your inner strength is more powerful than any external challenge.");
                quotesList.add("The future belongs to those who believe in the beauty of their dreams.");
                quotesList.add("Your potential is limitless. Stop doubting yourself and start creating.");
                quotesList.add("Greatness begins with the decision to believe in yourself.");
                quotesList.add("Confidence comes not from always being right, but from not fearing to be wrong.");
                quotesList.add("You are not what happened to you. You are what you choose to become.");
                quotesList.add("Don't let the fear of what could happen make nothing happen.");
                quotesList.add("You have everything it takes to go beyond your wildest dreams.");
                quotesList.add("The way you speak to yourself matters. Be kind to yourself.");
                quotesList.add("You are capable of achieving extraordinary things. Believe in that power.");
                quotesList.add("Your biggest obstacle is your own mind. Once you overcome self-doubt, there's nothing you can't do.");
                quotesList.add("You don't have to see the whole staircase, just take the first step. - Martin Luther King Jr.");
                quotesList.add("To believe in yourself is to trust in your own abilities.");
                quotesList.add("Be proud of how far you've come, and have faith in how far you can go.");
                quotesList.add("Don't let anyone's negativity define who you are.");
                quotesList.add("The only way to grow is by trusting in yourself and your potential.");
                quotesList.add("Believe in yourself, because you are capable of doing amazing things.");
                quotesList.add("Every day is a new opportunity to believe in your own magic.");
                quotesList.add("You are the author of your own story. Don't let anyone else write it for you.");
                quotesList.add("Confidence is silent. Insecurities are loud.");
                quotesList.add("Start where you are, use what you have, and do what you can.");
                quotesList.add("Be the change you want to see in yourself.");
                quotesList.add("The moment you start believing in yourself is the moment the world will start believing in you.");
                quotesList.add("You are stronger than your struggles and braver than your fears.");
                quotesList.add("You are worthy of all the wonderful things life has to offer.");
                quotesList.add("Believe in the power of yet. If you haven't succeeded, you just haven't succeeded *yet*.");
                quotesList.add("Self-confidence is not a gift, it's a skill you develop through practice.");
                quotesList.add("When you believe in yourself, you inspire others to do the same.");
                quotesList.add("Remember, you are always one decision away from a completely different life.");
                quotesList.add("You are not too old and it's never too late to be who you were meant to be.");
                quotesList.add("Success begins the moment you believe you can achieve it.");
                break;

            case "Believe it!":
                quotesList.add("Believe you can and you're halfway there. - Theodore Roosevelt");
                quotesList.add("You are braver than you believe, stronger than you seem, and smarter than you think. - A.A. Milne");
                quotesList.add("Don't wait for permission to be who you know you can be.");
                quotesList.add("Act as if what you do makes a difference. It does. - William James");
                quotesList.add("Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.");
                quotesList.add("To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson");
                quotesList.add("You are enough just as you are.");
                quotesList.add("The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt");
                quotesList.add("As soon as you trust yourself, you will know how to live. - Johann Wolfgang von Goethe");
                quotesList.add("You've always had the power, my dear, you just had to learn it for yourself. - Glinda the Good Witch");
                quotesList.add("Trust yourself. You know more than you think you do. - Benjamin Spock");
                quotesList.add("Confidence is not 'they will like me.' Confidence is 'I'll be fine if they don't.'");
                quotesList.add("No one can make you feel inferior without your consent. - Eleanor Roosevelt");
                quotesList.add("Self-confidence is the best outfit. Rock it and own it.");
                quotesList.add("The more you believe in yourself, the more the world will believe in you.");
                quotesList.add("Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett");
                quotesList.add("The greatest thing in the world is to know how to belong to oneself. - Michel de Montaigne");
                quotesList.add("Believe in your infinite potential. Your only limitations are those you set upon yourself. - Roy T. Bennett");
                quotesList.add("You are capable of amazing things.");
                quotesList.add("It's not who you are that holds you back, it's who you think you're not.");
                quotesList.add("The more you love yourself, the less nonsense you'll tolerate.");
                quotesList.add("You have within you right now, everything you need to deal with whatever the world can throw at you. - Brian Tracy");
                quotesList.add("Nothing can stop the man with the right mental attitude from achieving his goal; nothing on earth can help the man with the wrong mental attitude. - Thomas Jefferson");
                quotesList.add("Be fearless in the pursuit of what sets your soul on fire.");
                quotesList.add("Your life is as good as your mindset.");
                quotesList.add("With realization of one's own potential and self-confidence in one's ability, one can build a better world. - Dalai Lama");
                quotesList.add("To anyone that ever told you you're no good … they're no better. - Hayley Williams");
                quotesList.add("You are worthy of great things.");
                quotesList.add("Don't limit your challenges, challenge your limits.");
                quotesList.add("Start where you are. Use what you have. Do what you can. - Arthur Ashe");
                quotesList.add("Stand up straight and realize who you are, that you tower over your circumstances. - Maya Angelou");
                quotesList.add("Be yourself; everyone else is already taken. - Oscar Wilde");
                quotesList.add("Self-worth comes from one thing – thinking that you are worthy.");
                quotesList.add("Go confidently in the direction of your dreams. Live the life you have imagined. - Henry David Thoreau");
                quotesList.add("No one is you, and that is your power.");
                quotesList.add("She believed she could, so she did.");
                quotesList.add("Don't forget to tell yourself positive things daily! You must love yourself internally to glow externally.");
                quotesList.add("Your self-worth is determined by you. You don't have to depend on someone telling you who you are. - Beyoncé");
                quotesList.add("To love oneself is the beginning of a lifelong romance. - Oscar Wilde");
                quotesList.add("You are more powerful than you know; you are beautiful just as you are.");
                quotesList.add("You carry so much love in your heart. Give some to yourself.");
                quotesList.add("Self-belief and hard work will always earn you success. - Virat Kohli");
                quotesList.add("Be yourself, but always your better self. - Karl G. Maeser");
                quotesList.add("Doubt kills more dreams than failure ever will. - Suzy Kassem");
                quotesList.add("Love yourself first and everything else falls into line. You really have to love yourself to get anything done in this world. - Lucille Ball");
                quotesList.add("Owning our story and loving ourselves through that process is the bravest thing that we'll ever do. - Brené Brown");
                quotesList.add("You are not your mistakes; they are what you did, not who you are.");
                quotesList.add("The way to develop self-confidence is to do the thing you fear and get a record of successful experiences behind you. - William Jennings Bryan");
                quotesList.add("Be so completely yourself that everyone else feels safe to be themselves too.");
                quotesList.add("Don't be afraid to be who you are, and never be afraid to believe in yourself.");
                quotesList.add("If you don't believe in yourself, nobody else will.");
                quotesList.add("Your potential is endless. Go do what you were created to do.");
                quotesList.add("The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey");
                quotesList.add("Don't compare yourself with anyone in this world. If you do so, you are insulting yourself. - Bill Gates");
                quotesList.add("The moment you doubt whether you can fly, you cease forever to be able to do it. - J.M. Barrie");
                quotesList.add("You owe it to yourself to become everything you've ever dreamed of being.");
                quotesList.add("The only person who can pull me down is myself, and I'm not going to let myself pull me down anymore. - C. JoyBell C.");
                quotesList.add("When you believe in yourself, you have already taken the first step.");
                quotesList.add("Be your own kind of beautiful.");
                quotesList.add("Life shrinks or expands in proportion to one's courage. - Anaïs Nin");
                quotesList.add("The power you have is to be the best version of yourself you can be, so you can create a better world. - Ashley Rickards");
                quotesList.add("Follow your inner moonlight; don't hide the madness. - Allen Ginsberg");
                quotesList.add("Self-belief is the secret to success.");
                quotesList.add("Believe deep down in your heart that you're destined to do great things. - Joe Paterno");
                quotesList.add("You are stronger than you know, braver than you feel, and smarter than you think.");
                quotesList.add("Believe in yourself a little more.");
                quotesList.add("The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt");
                quotesList.add("Success comes from knowing that you did your best to become the best that you are capable of becoming. - John Wooden");
                quotesList.add("If you don't stand for something, you will fall for anything.");
                quotesList.add("Be the reason someone believes in the goodness of people.");
                quotesList.add("What you think of yourself is much more important than what people think of you.");
                quotesList.add("Be so busy improving yourself that you have no time to criticize others.");
                quotesList.add("You don't need anyone's permission to live your life.");
                quotesList.add("Remember who you are. You have so much to offer.");
                quotesList.add("Self-love is not selfish; you cannot truly love another until you know how to love yourself.");
                quotesList.add("Believe in yourself, for you are capable of achieving greatness.");
                quotesList.add("The most beautiful thing you can wear is confidence.");
                break;

            case "Feel it!":
                quotesList.add("The greatest glory in living lies not in never falling, but in rising every time we fall.");
                quotesList.add("In the middle of every difficulty lies opportunity.");
                quotesList.add("Your time is limited, don't waste it living someone else's life.");
                quotesList.add("Success is not final, failure is not fatal: It is the courage to continue that counts.");
                quotesList.add("What lies behind us and what lies before us are tiny matters compared to what lies within us.");
                quotesList.add("Believe you can and you're halfway there.");
                quotesList.add("The only way to do great work is to love what you do.");
                quotesList.add("Don't watch the clock; do what it does. Keep going.");
                quotesList.add("The future belongs to those who believe in the beauty of their dreams.");
                quotesList.add("It is during our darkest moments that we must focus to see the light.");
                quotesList.add("Act as if what you do makes a difference. It does.");
                quotesList.add("You miss 100% of the shots you don't take.");
                quotesList.add("The only limit to our realization of tomorrow will be our doubts of today.");
                quotesList.add("Opportunities don't happen. You create them.");
                quotesList.add("The way to get started is to quit talking and begin doing.");
                quotesList.add("Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.");
                quotesList.add("If you want to lift yourself up, lift up someone else.");
                quotesList.add("What we fear doing most is usually what we most need to do.");
                quotesList.add("Life is 10% what happens to us and 90% how we react to it.");
                quotesList.add("The only person you are destined to become is the person you decide to be.");
                quotesList.add("It does not matter how slowly you go as long as you do not stop.");
                quotesList.add("The harder the conflict, the more glorious the triumph.");
                quotesList.add("Everything you've ever wanted is on the other side of fear.");
                quotesList.add("You are never too old to set another goal or to dream a new dream.");
                quotesList.add("What you get by achieving your goals is not as important as what you become by achieving your goals.");
                quotesList.add("Your life does not get better by chance, it gets better by change.");
                quotesList.add("If you want to achieve greatness, stop asking for permission.");
                quotesList.add("Success usually comes to those who are too busy to be looking for it.");
                quotesList.add("Dream big and dare to fail.");
                quotesList.add("You must do the things you think you cannot do.");
                quotesList.add("Challenges are what make life interesting; overcoming them is what makes life meaningful.");
                quotesList.add("Success is how high you bounce when you hit bottom.");
                quotesList.add("You are braver than you believe, stronger than you seem, and smarter than you think.");
                quotesList.add("I am not a product of my circumstances. I am a product of my decisions.");
                quotesList.add("Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.");
                quotesList.add("Happiness is not something ready-made. It comes from your own actions.");
                quotesList.add("What we achieve inwardly will change outer reality.");
                quotesList.add("Strive not to be a success, but rather to be of value.");
                quotesList.add("Every moment is a fresh beginning.");
                quotesList.add("It's not whether you get knocked down, it's whether you get up.");
                quotesList.add("You can't use up creativity. The more you use, the more you have.");
                quotesList.add("Be yourself; everyone else is already taken.");
                quotesList.add("Do not wait to strike till the iron is hot, but make it hot by striking.");
                quotesList.add("The best time to plant a tree was twenty years ago. The second best time is now.");
                quotesList.add("An unexamined life is not worth living.");
                quotesList.add("The mind is everything. What you think you become.");
                quotesList.add("Life isn't about finding yourself. Life is about creating yourself.");
                quotesList.add("Nothing in life is to be feared, it is only to be understood.");
                quotesList.add("The only way to find true happiness is to risk being completely cut open.");
                quotesList.add("What you do speaks so loudly that I cannot hear what you say.");
                quotesList.add("Keep your face always toward the sunshine—and shadows will fall behind you.");
                quotesList.add("The best revenge is massive success.");
                quotesList.add("You have power over your mind—not outside events. Realize this, and you will find strength.");
                quotesList.add("Success is not how high you have climbed, but how you make a positive difference to the world.");
                quotesList.add("Failure is simply the opportunity to begin again, this time more intelligently.");
                quotesList.add("You cannot swim for new horizons until you have courage to lose sight of the shore.");
                quotesList.add("The secret of getting ahead is getting started.");
                quotesList.add("Turn your wounds into wisdom.");
                quotesList.add("Limit your 'always' and your 'nevers'.");
                quotesList.add("The journey of a thousand miles begins with one step.");
                quotesList.add("Everything has beauty, but not everyone sees it.");
                quotesList.add("Life is not measured by the number of breaths we take, but by the moments that take our breath away.");
                quotesList.add("Success is not in what you have, but who you are.");
                quotesList.add("Do not go where the path may lead, go instead where there is no path and leave a trail.");
                quotesList.add("Nothing is impossible, the word itself says 'I'm possible'!");
                quotesList.add("Keep your eyes on the stars, and your feet on the ground.");
                quotesList.add("The greatest mistake you can make in life is to be continually fearing you will make one.");
                quotesList.add("Life is short, and it is up to you to make it sweet.");
                quotesList.add("The more you praise and celebrate your life, the more there is in life to celebrate.");
                quotesList.add("Success is not for the lazy.");
                quotesList.add("When you reach the end of your rope, tie a knot in it and hang on.");
                quotesList.add("You can't have a million-dollar dream with a minimum-wage work ethic.");
                quotesList.add("Do what you can, with what you have, where you are.");
                quotesList.add("If you are not willing to risk the usual, you will have to settle for the ordinary.");
                quotesList.add("The only way to discover the limits of the possible is to go beyond them into the impossible.");
                quotesList.add("Success is stumbling from failure to failure with no loss of enthusiasm.");
                quotesList.add("Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.");
                quotesList.add("What we fear doing most is usually what we most need to do.");
                quotesList.add("Opportunities don't happen, you create them.");
                quotesList.add("It's not the years in your life that count. It's the life in your years.");
                quotesList.add("A person who never made a mistake never tried anything new.");
                quotesList.add("Success is often achieved by those who don't know that failure is inevitable.");
                quotesList.add("The only way to achieve the impossible is to believe it is possible.");
                quotesList.add("Every setback is a setup for a comeback.");
                quotesList.add("The best way to predict the future is to create it.");
                quotesList.add("Don't wait for opportunity. Create it.");
                quotesList.add("It always seems impossible until it's done.");
                quotesList.add("Do not wait for leaders; do it alone, person to person.");
                quotesList.add("Dream it. Wish it. Do it.");
                quotesList.add("Keep pushing yourself because no one else is going to do it for you.");
                quotesList.add("Hardships often prepare ordinary people for an extraordinary destiny.");
                quotesList.add("We may encounter many defeats, but we must not be defeated.");
                quotesList.add("Success is not how far you got, but the distance you traveled from where you started.");
                quotesList.add("You are stronger than you think, braver than you believe, and smarter than you know.");
                quotesList.add("Success is not about the destination, it's about the journey.");
                quotesList.add("Take the risk or lose the chance.");
                quotesList.add("If you want to be successful, focus on the solutions, not the problems.");
                quotesList.add("Dream big, start small, act now.");
                quotesList.add("Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.");
                quotesList.add("Success is the sum of small efforts, repeated day in and day out.");
                quotesList.add("Don't wait for the right opportunity. Create it.");
                quotesList.add("The difference between who you are and who you want to be is what you do.");
                quotesList.add("Success is the result of preparation, hard work, and learning from failure.");
                quotesList.add("Don't be afraid to give up the good to go for the great.");
                quotesList.add("What you get by achieving your goals is not as important as what you become by achieving your goals.");
                quotesList.add("Great things never come from comfort zones.");
                quotesList.add("Success is not final, failure is not fatal: It is the courage to continue that counts.");
                quotesList.add("Don't limit your challenges. Challenge your limits.");
                quotesList.add("It's never too late to be what you might have been.");
                quotesList.add("In the middle of difficulty lies opportunity.");
                quotesList.add("Act as if what you do makes a difference. It does.");
                quotesList.add("Life is 10% what happens to us and 90% how we react to it.");
                quotesList.add("Great things take time, and every journey starts with a single step.");
                quotesList.add("Success comes from knowing that you did your best to become the best that you are capable of becoming.");
                quotesList.add("Your limitations are only what you believe them to be.");
                quotesList.add("Success isn't just about what you accomplish in your life; it's about what you inspire others to do.");
                quotesList.add("Hard work beats talent when talent doesn't work hard.");
                quotesList.add("The only time success comes before work is in the dictionary.");
                quotesList.add("You can achieve anything if you just keep moving forward.");
                quotesList.add("Success isn't measured by what you achieve, but by what you overcome.");
                quotesList.add("If you want something you've never had, you must be willing to do something you've never done.");
                quotesList.add("Life is about making an impact, not making an income.");
                quotesList.add("Success is not in what you have, but who you are.");
                quotesList.add("Great things are never done by one person. They're done by a team of people.");
                quotesList.add("The best revenge is massive success.");
                quotesList.add("Don't wait for opportunities, create them.");
                quotesList.add("The journey of a thousand miles begins with one step.");
                quotesList.add("It's not about how bad you want it. It's about how hard you're willing to work for it.");
                quotesList.add("Success is not about being the best. It's about always getting better.");
                quotesList.add("Your future is created by what you do today, not tomorrow.");
                quotesList.add("Believe you can and you're halfway there.");
                quotesList.add("Life isn't about finding yourself. Life is about creating yourself.");
                quotesList.add("The only limit to our realization of tomorrow is our doubts of today.");
                quotesList.add("It's hard to beat a person who never gives up.");
                quotesList.add("Opportunities don't happen. You create them.");
                quotesList.add("The best way out is always through.");
                quotesList.add("Success is not in what you do, but who you become in the process.");
                quotesList.add("In the end, we only regret the chances we didn't take.");
                quotesList.add("You are the architect of your own future.");
                quotesList.add("Do not go where the path may lead, go instead where there is no path and leave a trail.");
                break;
        }
    }
}